config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books

  root 'home#top'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
	end
  
 #  resources :users,only: [:show,:index,:edit,:update] do
 #  resources :relationships, only: [:create, :destroy]
	# end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => 'relationships#index', as: 'index_relationship'
  get 'users/:id/followers' => 'relationships#new', as: 'new_relationship'

  get  'serched' => 'searches#search',  as: 'search'
  get  'serch_book' => 'searches#index',  as: 'search_book'
  get  'serche_user' => 'searches#new',  as: 'search_user'

  get 'maps/index'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
	end

	def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_place.html.erb
<% if book.favorited_by?(current_user) %>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
           <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
            <%= book.favorites.count %>
     <% end %>
<% else %>
     <%= link_to book_favorites_path(book), method: :post,remote: true do %>
          <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: gray;"></i>
          <%= book.favorites.count %>
     <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-<%= @book.id %>').html("<%= j(render partial: "favorite_place", locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorite-<%= @book.id %>').html("<%= j(render partial: "favorite_place", locals: {book: @book}) %>");