config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books

  root 'home#top'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
	end
  
 #  resources :users,only: [:show,:index,:edit,:update] do
 #  resources :relationships, only: [:create, :destroy]
	# end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => 'relationships#index', as: 'index_relationship'
  get 'users/:id/followers' => 'relationships#new', as: 'new_relationship'

  get  'serched' => 'searches#search',  as: 'search'
  get  'serch_book' => 'searches#index',  as: 'search_book'
  get  'serche_user' => 'searches#new',  as: 'search_user'

  get 'maps/index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

 	has_many :books, dependent: :destroy
 	has_many :post_comments, dependent: :destroy
 	has_many :favorites, dependent: :destroy
  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  	validates :introduction,    length: { maximum: 50} 

 #以下　フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
  unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

# ユーザー検索
  def self.search(keyword, search_name)
      if search_name == "完全一致"
        where(['name LIKE ?', "#{keyword}"])
      elsif search_name == "部分一致"
         where(['name LIKE ?', "%#{keyword}%"])
      elsif search_name == "前方一致"
        where(['name LIKE ?', "#{keyword}%"])
      elsif search_name == "後方一致"
        where(['name LIKE ?', "%#{keyword}"])
      else
      end
  end

# 住所検索
  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
    @book_new = Book.new
    #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book_new = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  
  def edit
   @user = User.find(params[:id])
      if @user == current_user

      else
        redirect_to user_path(current_user.id)
      end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

    def user_params
      params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
 
  <%= f.input :postcode %>
  <%= f.input :prefecture_code, collection: JpPrefecture::Prefecture.all, :value_method => :name, include_blank: '都道府県' %>
  <%= f.input :address_city %>
  <%= f.input :address_street %>
  <%= f.input :address_building %>
  
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th> フォロー数 : <%= link_to index_relationship_path(user) do %>
				<%= user.followings.count %></th>
				<% end %>
		</tr>
		<tr>
			<th>フォロワー数 :<%= link_to new_relationship_path(user) do %>
				<%= user.followers.count %></th>
				<% end %> 
		</tr>
		<tr><th><%= render 'relationships/follow_button', user: user %></th></tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
        <div class="alart-message">
           <h3 class="alart-body"><%= pluralize(@user.errors.count, "error") %> prohibited this userinfo from being saved:</h3>
          <ul>
             <% @user.errors.full_messages.each do |message| %>
                 <li><%= message %></li>
             <% end %>
          </ul>
      <% end %>


<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="body">
	<%= flash[:success] %>
	<%= flash[:alert] %>
    <div class="container">
<div class="row">
	<div class="col-xs-3">

<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book_new %>
	</div>

	<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td> フォロー数 : <%= link_to index_relationship_path(user) do %>
				<%= user.followings.count %></td>
				<% end %>
			<td>
			<th>フォロワー数 :<%= link_to new_relationship_path(user) do %>
				<%= user.followers.count %></td>
				<% end %> 
			<td><%= render 'relationships/follow_button', user: user %></td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
	</div>
	</div>
</div>
</div>

app/views/users/show.html.erb
	<%= flash[:success] %>
	<%= flash[:alert] %>
<h2>User info</h2>
<div class="body">
    <div class="container">
		<div class="row">
  			<div class="col-xs-3">
				<%= render 'users/profile', user: @user %>
			
<!--同コントローラーのviewで表示ならusersは省略可 -->

				<h2>New book</h2>
				<%= render 'books/newform', book: @book_new %>
				
			</div>
			<div class="col-xs-9">
				<h2>Books</h2>
<!--books一覧 -->
				<table class="table table-hover table-inverse">
				<thead>
					<tr>
					<th></th>
					<th>Title</th>
					<th>body</th>
					<th colspan="3"></th>
					</tr>
				</thead>

			<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
		<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td>コメント数 : <%= book.post_comments.count %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

</div>
</div>
	<div>
	</div>
	<% if current_user == @user %>
		<%= render 'maps/index', user: @user%>
	<% end %>
</div>
<!--books一覧 -->