config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books

  root 'home#top'
  get 'home/about'

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
	end
  
 #  resources :users,only: [:show,:index,:edit,:update] do
 #  resources :relationships, only: [:create, :destroy]
	# end
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => 'relationships#index', as: 'index_relationship'
  get 'users/:id/followers' => 'relationships#new', as: 'new_relationship'

  get  'serched' => 'searches#search',  as: 'search'
  get  'serch_book' => 'searches#index',  as: 'search_book'
  get  'serche_user' => 'searches#new',  as: 'search_user'

  get 'maps/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	
	 def favorited_by?(user)
            favorites.where(user_id: user.id).exists?
        end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	# book検索
	  def self.search(keyword, search_name)
      if search_name == "完全一致"
        where(['title LIKE ?', "#{keyword}"])
      elsif search_name == "部分一致"
         where(['title LIKE ?', "%#{keyword}%"])
      elsif search_name == "前方一致"
        where(['title LIKE ?', "#{keyword}%"])
      elsif search_name == "後方一致"
        where(['title LIKE ?', "%#{keyword}"])
      else
      end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

 	has_many :books, dependent: :destroy
 	has_many :post_comments, dependent: :destroy
 	has_many :favorites, dependent: :destroy
  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  	validates :introduction,    length: { maximum: 50} 

 #以下　フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
  unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

# ユーザー検索
  def self.search(keyword, search_name)
      if search_name == "完全一致"
        where(['name LIKE ?', "#{keyword}"])
      elsif search_name == "部分一致"
         where(['name LIKE ?', "%#{keyword}%"])
      elsif search_name == "前方一致"
        where(['name LIKE ?', "#{keyword}%"])
      elsif search_name == "後方一致"
        where(['name LIKE ?', "%#{keyword}"])
      else
      end
  end

# 住所検索
  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book_new = Book.new
    @book = Book.find(params[:id]) 
    @user = @book.user
    @post_comment_new = PostComment.new
  end


  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
    @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all

  		render 'index'
  	end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  	if @user == current_user

    else
      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def index
		
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def index
	end

	def new
	end

	def search 
		if params[:model_name] == "ユーザー"
			keyword = params[:keyword]
			search_name = params[:search_name]
			@searched_users = User.search(keyword,search_name)
			render 'new'
		elsif params[:model_name] == "ブック"
			keyword = params[:keyword]
			search_name = params[:search_name]
			@searched_books = Book.search(keyword,search_name)
			render 'index'
		else
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
    @book_new = Book.new
    #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book_new = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  
  def edit
   @user = User.find(params[:id])
      if @user == current_user

      else
        redirect_to user_path(current_user.id)
      end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

    def user_params
      params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li> 
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to(" sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up") %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
    </div>
  </body>
  <br>
         <!-- 検索機能 -->
        <% if user_signed_in? %>
         <%= form_tag(search_path, method: "get") do %>
          <%= text_field_tag :keyword,  params[:keyword], placeholder:"user名やbook名"%>
          <!-- プルダウン検索バー生成 -->
          <%= select_tag :model_name, options_for_select([["User", "ユーザー"], ["Books","ブック"]]) %>

          <%= select_tag :search_name, options_for_select([["完全一致", "完全一致"],["部分一致","部分一致"],["前方一致", "前方一致"],["後方一致","後方一致"]]) %>
          <%= submit_tag 'Search' %>
           <% end %>
        <% end %>


  <%= yield %>

  <footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
  </footer>


</html>